FROM ubuntu:bionic

#-----------------------------------------------
# MIN
#-----------------------------------------------

RUN apt-get update  -y && \
    apt-get install -y apt-utils

RUN apt-get update  -y && \
    apt-get install -y build-essential software-properties-common pkg-config

RUN apt-get install -y wget gawk tree boxes

RUN apt-get install -y curl

RUN apt-get update -y && \
    apt-get install -y ffmpeg

RUN apt-get update -y && \
    apt-get install -y portaudio19-dev

RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip install --upgrade pip setuptools wheel

RUN pip install pyaudio
RUN pip install termcolor

#+------------------------------------------------------------+
#| GOOGLE CLOUD SDK                                           |
#| https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu |
#+------------------------------------------------------------+

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

#https://cloud.google.com/speech-to-text/docs/reference/libraries#client-libraries-install-python

RUN pip install --upgrade google-cloud-speech
RUN pip install --upgrade google-cloud-storage

RUN /usr/bin/python3 -m pip install --upgrade pip

RUN pip install pysrt
RUN pip install numpy

RUN apt-get install -y moreutils

#+---------------+
#| PROJECT FILES |
#+---------------+

# mapped using -v
