FROM ubuntu:bionic

#-----------------------------------------------
# MIN
#-----------------------------------------------

RUN apt-get update  -y && \
    apt-get install -y apt-utils

RUN apt-get update  -y && \
    apt-get install -y build-essential software-properties-common pkg-config

RUN apt-get install -y wget gawk tree boxes

RUN apt-get install -y curl

RUN apt-get update -y && \
    apt-get install -y ffmpeg

RUN apt-get update -y && \
    apt-get install -y portaudio19-dev

RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip install --upgrade pip setuptools wheel

RUN pip install pyaudio
RUN pip install termcolor

#+------------------------------------------------------------+
#| GOOGLE CLOUD SDK                                           |
#| https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu |
#+------------------------------------------------------------+

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

#https://cloud.google.com/speech-to-text/docs/reference/libraries#client-libraries-install-python

RUN pip install --upgrade google-cloud-speech
RUN pip install --upgrade google-cloud-storage

RUN /usr/bin/python3 -m pip install --upgrade pip

RUN pip install pysrt
RUN pip install numpy

RUN apt-get install -y moreutils

#+---------------+
#| PROJECT FILES |
#+---------------+

RUN  mkdir /ssttg
RUN  mkdir /ssttg/hmzcode

COPY \
  audio_depacketizer.c          \
  audio_packetizer.c            \
  common_bash_functions.sh      \
  readme.txt                    \
  run_ut.sh                     \
  sstt_testclip_20_sec.mp4      \
  ssttg.sh                      \
  ssttg_dev_run_ut_clean_in_docker.sh   \
  ssttg_dev_run_ut_in_docker.sh         \
  /ssttg/

RUN  gcc -o /ssttg/audio_packetizer   /ssttg/audio_packetizer.c
RUN  gcc -o /ssttg/audio_depacketizer /ssttg/audio_depacketizer.c

COPY \
  hmzcode/amg_logger.py             \
  hmzcode/streaming_stt.py          \
  hmzcode/stt_cmdargs.py            \
  hmzcode/stt_commons.py            \
  hmzcode/stt_config_fnxs.py        \
  hmzcode/stt_config_vars.py        \
  hmzcode/stt_default_config.py     \
  hmzcode/stt_globals.py            \
  hmzcode/stt_google_response_interface.py  \
  hmzcode/stt_packpcm_reader.py     \
  hmzcode/stt_pcm_stream_state.py   \
  hmzcode/stt_srt_writer.py         \
  /ssttg/hmzcode/

COPY test/ /ssttg/

RUN tree /ssttg

